# Generated by Django 5.0.4 on 2024-07-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paaark',
            options={'verbose_name': 'Licence Plate Detail', 'verbose_name_plural': 'Licence Plate Details'},
        ),
    ]
